---
- name: Register repo
  include_tasks: "register_repo.yml"
  when: meta.repo_name is defined 
- name: Deploy chart from local path
  kubernetes.core.helm:
    binary_path: "{{ helm_binary }}"
    name: "{{ meta.chart_release_name }}"
    chart_ref: "{{ meta.repo_name }}/{{ meta.chart_name}}"
    chart_version: "{{ meta.chart_source_version | default(omit) }}"
    namespace: "{{ meta.helm_namespace }}" 
    create_namespace: true
    #kubeconfig: "{{ meta.context }}"
    ca_cert: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    values_files:
      - "{{ meta.role_path }}/values.yaml"
  register: install
  when: helmoperator_resource_state is not defined 
- name: "Assert that {{ meta.chart_release_name }} is installed from {{ meta.chart_source }} "
  assert:
    that:
      - install.status.status | lower == 'deployed'
  when: helmoperator_resource_state is not defined 
- name: Delete Chart with wait
  kubernetes.core.helm:
    state: absent 
    binary_path: "{{ helm_binary }}"
    name: "{{ meta.chart_release_name }}"
    namespace: "{{ meta.helm_namespace }}"
    wait: yes
  register: uninstall
  when: helmoperator_resource_state is defined and helmoperator_resource_state == 'absent' 

- name: assert warning has been raised
  assert:
    that:
      - uninstall.warnings
  ignore_errors: yes
  when: helmoperator_resource_state is defined and helmoperator_resource_state == 'absent' 
