# permissions for end users to view helmoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helmoperator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: helm-operator
    app.kubernetes.io/part-of: helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: helmoperator-viewer-role
rules:
- apiGroups:
  - helmoperator.example.com
  resources:
  - helmoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helmoperator.example.com
  resources:
  - helmoperators/status
  verbs:
  - get
